<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
		<PackageReference Include="Google.GenAI" Version="1.6.2" />
		<PackageReference Include="Google_GenerativeAI" Version="3.6.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Credentials\wh-store-drive-91de808a7958.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties credentials_4wh-store-drive-91de808a7958_1json__JsonSchema="Copy to Output Directory" /></VisualStudio></ProjectExtensions>

</Project>
