// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace whstore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425032859_InitialDBSetup")]
    partial class InitialDBSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("whstore.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffiliateLink")
                        .HasColumnType("text")
                        .HasColumnName("affiliatelink");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CommissionRate")
                        .HasColumnType("text")
                        .HasColumnName("commissionrate");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsHotProduct")
                        .HasColumnType("boolean")
                        .HasColumnName("ishotproduct");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("OriginalPrice")
                        .HasColumnType("text")
                        .HasColumnName("originalprice");

                    b.Property<string>("Price")
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .HasColumnType("text")
                        .HasColumnName("productid");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text")
                        .HasColumnName("producturl");

                    b.Property<string>("ReviewCount")
                        .HasColumnType("text")
                        .HasColumnName("reviewcount");

                    b.Property<string>("ReviewRate")
                        .HasColumnType("text")
                        .HasColumnName("reviewrate");

                    b.Property<string>("ShippingCost")
                        .HasColumnType("text")
                        .HasColumnName("shippingcost");

                    b.Property<string>("StoreName")
                        .HasColumnType("text")
                        .HasColumnName("storename");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
