// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using whstore.Data;

#nullable disable

namespace whstore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606054252_FinalCleanStart")]
    partial class FinalCleanStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("whstore.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffiliateLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("affiliatelink");

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("CommissionRate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commissionrate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsHotProduct")
                        .HasColumnType("bit")
                        .HasColumnName("ishotproduct");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("lastupdated")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OriginalPrice")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("originalprice");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("price");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("producturl");

                    b.Property<string>("ReviewCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reviewcount");

                    b.Property<string>("ReviewRate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reviewrate");

                    b.Property<string>("ShippingCost")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shippingcost");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storename");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
