// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using whstore.Data;

#nullable disable

namespace whstore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("whstore.Models.EmbedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmbedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Embeds");
                });

            modelBuilder.Entity("whstore.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AffiliateLink")
                        .HasColumnType("text")
                        .HasColumnName("affiliatelink");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CommissionRate")
                        .HasColumnType("text")
                        .HasColumnName("commissionrate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsHotProduct")
                        .HasColumnType("boolean")
                        .HasColumnName("ishotproduct");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("OriginalPrice")
                        .HasColumnType("text")
                        .HasColumnName("originalprice");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text")
                        .HasColumnName("producturl");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviewcount");

                    b.Property<string>("ReviewRate")
                        .HasColumnType("text")
                        .HasColumnName("reviewrate");

                    b.Property<string>("ShippingCost")
                        .HasColumnType("text")
                        .HasColumnName("shippingcost");

                    b.Property<string>("StoreName")
                        .HasColumnType("text")
                        .HasColumnName("storename");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
